version: "3.8"

services:
  web:
    image: sit725-skipy-image:latest
    container_name: sit725-skipy
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=development
      - DB_USERNAME= admin
      - DB_PWD= rUjWflR5hDq8WquA
      - DB_PORT=27017
      - DB_NAME=sit725-skipy
    depends_on:
      - db
    volumes:
      - ./my-web-app:/app
    command: ["npm", "server.js"]

volumes:
  db-data:
